### ISSUE TITLE
SVG files does not match the png files

### ISSUE THREAD

**Issue by whiteyhat** [bitficus/theSat#1]
## Introduction
This logo should become a standard to use for sats. However, there are no similarities between files.

**Comment by bitficus** [comment]
Thanks for supporting the sat! Perhaps I should make a note about the differences in the characters, which may help.

"the sat" as purposed on this repo isn't a logo, the same way that "@" is not a logo. The idea is that "$@" is its own character, which would be reproduced in various typefaces, each appropriate for their specific UX platform. The varying styles and typefaces on this repo is for this reason.

**Comment by whiteyhat** [comment]
I see! Good job!!
